### ISSUE TITLE
[BUG] Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by gajus** [npm/arborist#116]
```bash
$ echo '{ "dependencies": { "@storybook/react": "^6.0.12", "react": "0.0.0-experimental-94c0244ba" } }' > package.json
$ npm --version
7.0.0-beta.6
$ npm install

```

Produces error:

```log
npm ERR! Cannot read property 'name' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gajus/.npm/_logs/2020-08-24T22_09_18_065Z-debug.log

```

Debug log describes:

```
35 verbose stack TypeError: Cannot read property 'name' of undefined
35 verbose stack     at Arborist.[canPlaceDep] (/Users/gajus/.nvm/versions/node/v14.5.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:989:33)
35 verbose stack     at Arborist.[placeDep] (/Users/gajus/.nvm/versions/node/v14.5.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:803:36)
35 verbose stack     at Arborist.[placeDep] (/Users/gajus/.nvm/versions/node/v14.5.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:926:45)
35 verbose stack     at Arborist.[placeDep] (/Users/gajus/.nvm/versions/node/v14.5.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:926:45)
35 verbose stack     at /Users/gajus/.nvm/versions/node/v14.5.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:643:46
35 verbose stack     at Array.map (<anonymous>)
35 verbose stack     at Arborist.[buildDepStep] (/Users/gajus/.nvm/versions/node/v14.5.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:643:8)
35 verbose stack     at async Arborist.buildIdealTree (/Users/gajus/.nvm/versions/node/v14.5.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:168:7)
35 verbose stack     at async Promise.all (index 1)
35 verbose stack     at async Arborist.reify (/Users/gajus/.nvm/versions/node/v14.5.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:125:5)

```

**Comment by isaacs** [comment]
fixed in arborist 0.0.20, will be fixed in next npm beta.
