### ISSUE TITLE
[BUG] Cannot read property 'extraneous' of undefined

### ISSUE THREAD

**Issue by wolfie** [npm/arborist#222]
# What / Why
It seems like with a certain setup using npm workspaces that has an internal dependency-tree (npm 7.5.1), running `npm install` causes this error:

```
% npm install
npm ERR! Cannot read property 'extraneous' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hpaul/.npm/_logs/2021-02-08T15_37_33_410Z-debug.log
```

the npm log includes this piece of snippet:

```
24 verbose stack TypeError: Cannot read property 'extraneous' of undefined
24 verbose stack     at Arborist.[loadVirtualLink] (/Users/hpaul/.nvm/versions/node/v15.8.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-virtual.js:268:30)
24 verbose stack     at Arborist.[resolveLinks] (/Users/hpaul/.nvm/versions/node/v15.8.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-virtual.js:195:34)
24 verbose stack     at async Arborist.[loadFromShrinkwrap] (/Users/hpaul/.nvm/versions/node/v15.8.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-virtual.js:88:5)
24 verbose stack     at async Arborist.loadVirtual (/Users/hpaul/.nvm/versions/node/v15.8.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-virtual.js:66:5)
24 verbose stack     at async Arborist.buildIdealTree (/Users/hpaul/.nvm/versions/node/v15.8.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:206:7)
24 verbose stack     at async Promise.all (index 1)
24 verbose stack     at async Arborist.reify (/Users/hpaul/.nvm/versions/node/v15.8.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:127:5)
24 verbose stack     at async install (/Users/hpaul/.nvm/versions/node/v15.8.0/lib/node_modules/npm/lib/install.js:38:3)
```

## When
I'm unsure what exactly causes this. But basically when I run `npm install`

## Where
Private repository

**Comment by ljharb** [comment]
What happens on v7.5.3?

**Comment by wolfie** [comment]
Unfortunately I was unable to find a way to install v7.5.3 on my computer (can you guide me towards how to find/install it on MacOS?).

However, I did install node nightly with `NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly/ nvm i node` which gave me v7.5.2. That gives me the same results.

**Comment by wraithgar** [comment]
7.5.3 is not out yet

**Comment by wolfie** [comment]
I fixed it on my machine by 
1) deleting `~/.npm` (did not help by itself)
2) deleting `node_modules` and `package-lock.json` in the project. (this helped)

**Comment by isaacs** [comment]
I would be very surprised if deleting `~/.npm` would have any effect.  That'll just trade some speed for a bit of disk space.  (If it _had_ helped, that might've pointed to a very bizarre race condition somewhere, but by this point, those code paths are pretty solid.)

Deleting `node_modules` and `package-lock.json` makes me think that there was a problem with the data somewhere in your project.  Maybe a very old lockfile that was not upgraded properly at some point?  Running `npm update` would have had the same effect, for future reference.

Leaving this open so we can take a look and see if that code path has any obvious issues, but glad to hear you got this worked out.

**Comment by isaacs** [comment]
Looking at the code, it seems like this would happen if you had a symlink dependency in the lockfile which did not have a target defined in the lockfile.  We should see if we can reproduce it synthetically and handle it better (likely by either defining the target as best we can, or just ignoring the link), but that really _should_ be impossible, so something definitely got wonky with your lockfile along the way.

**Comment by lenolib** [comment]
Missing symlinks triggered this for me.
I had a local dependency set up through the new npm workspaces, linked it through `npm install`, and then _renamed_ the dependency, which made arborist unhappy. Could fix it by removing the relevant lines in the package-lock.json.

**Comment by davidskuza** [comment]
What's the point of local file:// path dependencies if we can't use them. 

Simple example for containers, frontend does have dependency as `file://../pivot`. It fails at second `npm ci` in frontend. Can't even bypass with `npm i`.

```Dockerfile
WORKDIR /app

COPY ./pivot ./pivot
COPY ./frontend ./frontend

WORKDIR /app/pivot
RUN npm ci
RUN npm run build

WORKDIR /app/frontend
RUN npm ci
RUN npm run build
```

Also `npm ci` fails with that "you need package-lock.json" line but I got here by using `--verbose`.
