### ISSUE TITLE
[BUG] loadVirtual errors do not get forwarded to the promise correctly

### ISSUE THREAD

**Issue by kumavis** [npm/arborist#238]
# What / Why

version `2.2.3`

UnhandledPromiseRejectionWarning

arborist seems to somehow not be handling its own errors
my guess is it has to do with how the mixins are applied?

the error itself is not of concern

**see that the console log after the await-ed `loadVirtual` is reached**

```js
  const arb = new Arborist({
    path: projectRoot,
  })
  const tree = await arb.loadVirtual()
  console.log('loaded tree')
```

```
➜ node src/index.js
(node:20476) UnhandledPromiseRejectionWarning: Error: loadVirtual requires existing shrinkwrap file
    at Arborist.loadVirtual (/home/xyz/Development/lavamoat/node_modules/@npmcli/arborist/lib/arborist/load-virtual.js:57:18)
    at async doArborist (/home/xyz/Development/lavamoat/packages/lava-tree/src/index.js:43:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:20476) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20476) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
loaded tree <-------------
```

**Comment by kumavis** [comment]
whoops nvm
