### ISSUE TITLE
[doc] document when a node would not contain a resolved field

### ISSUE THREAD

**Issue by kumavis** [npm/arborist#239]
the resolved field is critical to understanding the provenance of a package for security reasons

its confusing when `arborist` is unable to determine where a package was resolved from
I can understand there are some situations when a package may not have a straight-forward resolved value, perhaps when it is a "bundled" dependency

it would be nice to know all the cases where this is possible and why

**Comment by kumavis** [comment]
this situation may be further complicated by loading an actual tree with a `yarn.lock` rather than a `package-lock.json`

**Comment by kumavis** [comment]
in this particular situation im seeing a non-peer non-bundled `assemblyscript` node appear without a resolved field.

parent package `rabin-warm@0.0.8` lists its dependency `"assemblyscript": "github:assemblyscript/assemblyscript#v0.6"`
in `yarn.lock` this appears as
```
rabin-wasm@~0.0.4:
  version "0.0.8"
  resolved "https://registry.yarnpkg.com/rabin-wasm/-/rabin-wasm-0.0.8.tgz#5b61b1d519d0377453435fbca5f82510b3f956cb"
  integrity sha512-TpIki3NG/X7nPnYHtYdF4Vp5NLrHvztiM5oL8+9NoeX/ClUfUyy7Y7DMrESZl1ropCpZJAjFMv/ZHYrkLu3bCQ==
  dependencies:
    assemblyscript "github:assemblyscript/assemblyscript#v0.6"
    bl "^1.0.0"
    debug "^4.1.1"
    minimist "^1.2.0"
    node-fetch "^2.6.0"
    readable-stream "^2.0.4"

"assemblyscript@github:assemblyscript/assemblyscript#v0.6":
  version "0.6.0"
  resolved "https://codeload.github.com/assemblyscript/assemblyscript/tar.gz/3ed76a97f05335504166fce1653da75f4face28f"
  dependencies:
    "@protobufjs/utf8" "^1.1.0"
    binaryen "77.0.0-nightly.20190407"
    glob "^7.1.3"
    long "^4.0.0"
    opencollective-postinstall "^2.0.0"
    source-map-support "^0.5.11"
```

**Comment by ljharb** [comment]
In npm 7, I’ve seen this field not show up reliably; but there’s now `npm explain assemblyscript` which may help?

**Comment by kumavis** [comment]
so i setup a set/get for Node.prototype.resolved and recorded all sets callee via error.stack parsing
here are all resolution sets https://gist.github.com/kumavis/699a356a908b61e4f7bc6599e5540044

majority are resolved and look like this:
```
resolutions /home/xyz/Development/metamask-extension/node_modules/3box/node_modules/did-jwt 
 [
  {
    value: null,
    callee: '    at new Node (/home/xyz/Development/lavamoat/node_modules/@npmcli/arborist/lib/node.js:126:19)'
  },
  {
    value: null,
    callee: '    at Shrinkwrap.add (/home/xyz/Development/lavamoat/node_modules/@npmcli/arborist/lib/shrinkwrap.js:722:23)'
  },
  {
    value: 'https://registry.yarnpkg.com/did-jwt/-/did-jwt-0.2.0.tgz',
    callee: '    at Shrinkwrap.addEdge (/home/xyz/Development/lavamoat/node_modules/@npmcli/arborist/lib/shrinkwrap.js:767:19)'
  }
]
```
there a dozen or without resolved https://gist.github.com/kumavis/dd779854be652536cc0850e740b40860
and they all look like this
```
resolutions /home/xyz/Development/metamask-extension/node_modules/acorn-jsx/node_modules/acorn 
 [
  {
    value: null,
    callee: '    at new Node (/home/xyz/Development/lavamoat/node_modules/@npmcli/arborist/lib/node.js:126:19)'
  },
  {
    value: null,
    callee: '    at Shrinkwrap.add (/home/xyz/Development/lavamoat/node_modules/@npmcli/arborist/lib/shrinkwrap.js:722:23)'
  }
]
```
theres lots of aborts (early returns in `addEdge`), so thats a potential culprit https://github.com/npm/arborist/blob/31516bffec65c7485f20e90e159c8262c6c1fca0/lib/shrinkwrap.js#L740-L777
tho only one of the missing hits these (mismatched version)

**Comment by kumavis** [comment]
many many edges are skipped because `edge.valid` is false, but these dont correspond to the nodes without `resolved` set
