### ISSUE TITLE
[BUG] Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by MarkPWebb** [npm/arborist#245]
# What / Why
While attempting to run `npm init fastify` in a new project I got the following error. The project is practically empty as I'm following through a tutorial.

```
723 verbose stack TypeError: Cannot read property 'version' of undefined
723 verbose stack     at Arborist.[saveIdealTree] (/mnt/Storage/mark/.nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:893:33)
723 verbose stack     at /mnt/Storage/mark/.nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:134:39
723 verbose stack     at async Arborist.reify (/mnt/Storage/mark/.nvm/versions/node/v14.16.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:130:5)
723 verbose stack     at async exec (/mnt/Storage/mark/.nvm/versions/node/v14.16.0/lib/node_modules/npm/lib/exec.js:234:7)
```

## When
When running `npm init fastify`

## Where

* n/a

### Current Behavior
I simply run `npm init fastify`. The only thing I can thing of is that perhaps it's due to there being no, or an empty, package.json.

I'm using node v14.16.0 and npm v7.5.6

**Comment by wraithgar** [comment]
This was a bug with unresolved peer dependencies. The output for this explains the conflict now, and the install succeeds.
