### ISSUE TITLE
[BUG] Issue of new version 2.7.1

### ISSUE THREAD

**Issue by PankajaChaudhari** [npm/arborist#304]
# Getting error for latest version dependency
```

Error we are getting is:

 error Couldn't find any versions for "@npmcli/arborist" that matches "^2.7.1"

info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

 Error: Couldn't find any versions for "make-fetch-happen" that matches "^9.0.4"

at MessageError.ExtendableBuiltin (/opt/yarn-v1.22.5/lib/cli.js:721:66)

at new MessageError (/opt/yarn-v1.22.5/lib/cli.js:750:123)

```

**Comment by wraithgar** [comment]
This is either a problem with the registry you are using, or the cli you are using.  These versions definitely do exist and I was able to install them just fine.
